data<-read.csv("household_power_consumption.txt", sep=";")
dataSubSet<-data[data$Date=="1/2/2007"|data$Date=="2/2/2007",]
dataSubSet$datetime<-as.POSIXct(paste(dataSubSet$Date, dataSubSet$Time),format="%d/%m/%Y %H:%M:%S")
plot(dataSubSet$datetime,as.numeric(as.character(dataSubSet$Sub_metering_1)), type="n",xlab="", ylab="Energy sub metering")
points(dataSubSet$datetime,as.numeric(as.character(dataSubSet$Sub_metering_1)), type="l",col="black")
points(dataSubSet$datetime,as.numeric(as.character(dataSubSet$Sub_metering_2)), type="l",col="red")
points(dataSubSet$datetime,as.numeric(as.character(dataSubSet$Sub_metering_3)), type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black", "red","blue"))
dev.copy(png,file="plot3.png")
dev.off()